// <auto-generated />
using System;
using AzureFunctionsApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzureFunctionsApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190414104640_notifications2")]
    partial class notifications2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureFunctionsApp.Models.Authentication", b =>
                {
                    b.Property<string>("AuthenticationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<int>("UserID");

                    b.HasKey("AuthenticationID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Authentication");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileLocation");

                    b.Property<string>("FileName");

                    b.Property<bool>("IsProfilePicture");

                    b.Property<int?>("UserID");

                    b.HasKey("DocumentID");

                    b.HasIndex("UserID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageName");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.MaritalStatus", b =>
                {
                    b.Property<int>("MaritalStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaritalStatusName")
                        .IsRequired();

                    b.HasKey("MaritalStatusID");

                    b.ToTable("MaritalStatuses");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.Property<int?>("UserID");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Session", b =>
                {
                    b.Property<int>("SessionTokenID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SessionToken")
                        .IsRequired();

                    b.Property<int?>("UserID");

                    b.HasKey("SessionTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SkillName");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LeaderID");

                    b.Property<string>("ProjectName");

                    b.Property<string>("TeamName")
                        .IsRequired();

                    b.HasKey("TeamID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<DateTime>("DateTimeUpdated");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<int?>("MaritalStatusID");

                    b.Property<string>("MedicalStatus");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Nationality");

                    b.Property<string>("NextOfKin1");

                    b.Property<string>("NextOfKin2");

                    b.Property<string>("PhoneToken");

                    b.Property<int>("RoleID");

                    b.Property<int?>("TeamID");

                    b.Property<int?>("UserTypeID");

                    b.Property<string>("VisaStatus");

                    b.HasKey("UserID");

                    b.HasIndex("MaritalStatusID");

                    b.HasIndex("RoleID");

                    b.HasIndex("TeamID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.UserLanguage", b =>
                {
                    b.Property<int>("UserLanguageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LanguageID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserLanguageID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.UserSkill", b =>
                {
                    b.Property<int>("UserSkillID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SkillID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserSkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserTypeName")
                        .IsRequired();

                    b.HasKey("UserTypeID");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Authentication", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.User", "User")
                        .WithOne("Authentication")
                        .HasForeignKey("AzureFunctionsApp.Models.Authentication", "UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Document", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Notification", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.Session", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.User", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.MaritalStatus", "MaritalStatus")
                        .WithMany("Users")
                        .HasForeignKey("MaritalStatusID");

                    b.HasOne("AzureFunctionsApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AzureFunctionsApp.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamID");

                    b.HasOne("AzureFunctionsApp.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.UserLanguage", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageID");

                    b.HasOne("AzureFunctionsApp.Models.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("AzureFunctionsApp.Models.UserSkill", b =>
                {
                    b.HasOne("AzureFunctionsApp.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillID");

                    b.HasOne("AzureFunctionsApp.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
